// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cineverse/AdminDashboard.tsx": () => import("../components/mockups/cineverse/AdminDashboard.tsx"),
  "./components/mockups/cineverse/BookingHistory.tsx": () => import("../components/mockups/cineverse/BookingHistory.tsx"),
  "./components/mockups/cineverse/Homepage.tsx": () => import("../components/mockups/cineverse/Homepage.tsx"),
  "./components/mockups/cineverse/HomepageA_Cinematic.tsx": () => import("../components/mockups/cineverse/HomepageA_Cinematic.tsx"),
  "./components/mockups/cineverse/HomepageB_MoodFirst.tsx": () => import("../components/mockups/cineverse/HomepageB_MoodFirst.tsx"),
  "./components/mockups/cineverse/HomepageC_QuickBook.tsx": () => import("../components/mockups/cineverse/HomepageC_QuickBook.tsx"),
  "./components/mockups/cineverse/HomepageD_SocialCity.tsx": () => import("../components/mockups/cineverse/HomepageD_SocialCity.tsx"),
  "./components/mockups/cineverse/LoginPage.tsx": () => import("../components/mockups/cineverse/LoginPage.tsx"),
  "./components/mockups/cineverse/MovieDetail.tsx": () => import("../components/mockups/cineverse/MovieDetail.tsx"),
  "./components/mockups/cineverse/PaymentPage.tsx": () => import("../components/mockups/cineverse/PaymentPage.tsx"),
  "./components/mockups/cineverse/SeatSelection.tsx": () => import("../components/mockups/cineverse/SeatSelection.tsx")
};
